# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop
- features/*
- bugfixes/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  spaApplicationRoot: './Application.Frontend/ClientApp'

steps:
- task: DotNetCoreCLI@2
  displayName: 'nuget restore'
  inputs:
    command: 'restore'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) --no-restore'
- task: Npm@1
  displayName: 'npm Restore'
  inputs:
    command: 'install'
    workingDir: '$(spaApplicationRoot)'
- task: Npm@1
  displayName: npm Build
  inputs:
    command: 'custom'
    customCommand: 'build $(spaApplicationRoot)'
- task: Npm@1
  displayName: ng Lint
  inputs:
    command: 'custom'
    customCommand: 'run --prefix $(spaApplicationRoot) lint'